# Generated by Django 4.1.5 on 2023-09-11 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPerfiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='cargar',
        ),
    ]
