# Generated by Django 4.1.5 on 2023-09-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPerfiles', '0002_rename_usuario_cargar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargar',
            name='contraseña',
        ),
    ]
